local suites = {
    { "Core", "core" },
    { "FileDialogFilter", "unit" },
    { "Physics", "core" },
    { "Project", "unit" },
    { "Scene", "core" },
    { "Scripting", "scripting" },
    { "ScriptMarshalling", "scripting" },
    { "App", "graphical" },
    { "ProjectExport", "graphical" },
    { "Renderer", "graphical" },
}

local function CTestPath(value)
    return value:gsub("\\", "/"):gsub('"', '\\"')
end

function WriteCTestFiles()
    local executableExtension = os.host() == "windows" and ".exe" or ""
    local workingDirectory = CTestPath(path.join(EppoRoot, "EppoEditor"))
    local configurations = { "Debug", "Release", "Dist" }

    for _, configuration in ipairs(configurations) do
        local testDirectory = path.join(EppoRoot, "build", "bin", configuration .. "-" .. os.target() .. "-x86_64")
        os.mkdir(testDirectory)
        local testExecutable = CTestPath(path.join(testDirectory, "EppoEngineTesting", "EppoEngineTesting" .. executableExtension))
        local manifest = assert(io.open(path.join(testDirectory, "CTestTestfile.cmake"), "w"))
        manifest:write("# Generated by Premake for standalone CTest discovery.\n")
        for _, suite in ipairs(suites) do
            manifest:write(string.format('add_test(%s "%s" "%s")\n', suite[1], testExecutable, suite[1]))
            manifest:write(string.format(
                'set_tests_properties(%s PROPERTIES WORKING_DIRECTORY "%s" LABELS "%s")\n',
                suite[1], workingDirectory, suite[2]))
        end
        manifest:close()
    end
end
