name: EppoEngine CI

on:
  workflow_dispatch:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: [ self-hosted, windows ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive