name: CI

on:
  workflow_dispatch:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  config-matrix:
    runs-on: [ windows-latest ]
    name: "Build and Test"
    strategy:
      matrix:
        config: [ Debug, Release, Dist ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Premake
        uses: abel0b/setup-premake@v2.3
        with:
          version: "5.0.0-beta2"
          path: Vendor/Premake/Bin

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Cache VulkanSDK
        id: cache-vulkansdk
        uses: actions/cache@v4
        with:
          path: "C:/VulkanSDK"
          key: vulkansdk

      - name: Download and Install VulkanSDK
        if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/1.3.275.0/windows/VulkanSDK-1.3.275.0-Installer.exe -OutFile VulkanSDK.exe
          .\VulkanSDK.exe --accept-licenses --default-answer --confirm-command install com.lunarg.vulkan.debug
      
      - name: Run Premake
        run: .\Vendor\Premake\Bin\Premake5.exe vs2022

      - name: "Build"
        run: msbuild /m /p:Configuration=${{ matrix.config }} EppoEngine.sln

      - name: "Test"
        run: .\Bin\${{ matrix.config }}-windows-x86_64\EppoTesting\EppoTesting.exe --gtest_output="xml:${{env.RUNNER_TEMP}}\testoutput.xml"
      
      - name: "Save test output"
        uses: actions/upload-artifact@v3
        with:
          name: TestOutput-${{ matrix.config }}
          path: ${{env.RUNNER_TEMP}}/testoutput.xml
