name: Test Report

on:
  workflow_run:
    workflows: [ CI ]
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  config-matrix:
    runs-on: [ windows-latest ]
    name: "Create test report"
    strategy:
      matrix:
        config: [ Debug, Release, Dist ]
    steps:
      - name: "Create test report"
        uses: dorny/test-reporter@v1
        with:
          artifact: TestOutput-${{ matrix.config }}
          name: Test Report ${{ matrix.config }}
          path: '*.xml'
          reporter: jest-junit
